[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "typing"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini-options]
adopts = "--cov=verbose_print"
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.black]
line-length = 80
target-version = ['py37']